In [18]:
# importing libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
import seaborn as sns
from datetime import datetime, timedelta

import plotly.express as px
import plotly.graph_objects as go

plt.style.use("ggplot")

pd.set_option('display.max_columns', None)

In [19]:
# Reading the dataset
df = pd.read_csv("../data/Afficionado Coffee Roasters.xlsx - Transactions (2).csv")

# Display rows of the dataframe
df.head

<bound method NDFrame.head of         transaction_id  year transaction_time  transaction_qty  store_id  \
0                    1  2025          7:06:11                2         5
1                    2  2025          7:08:56                2         5
2                    3  2025          7:14:04                2         5
3                    4  2025          7:20:24                1         5
4                    5  2025          7:22:41                2         5
...                ...   ...              ...              ...       ...
149111          149452  2025         20:18:41                2         8
149112          149453  2025         20:25:10                2         8
149113          149454  2025         20:31:34                1         8
149114          149455  2025         20:57:19                1         8
149115          149456  2025         20:57:19                2         8

         store_location  product_id  unit_price    product_category  \
0       Lower Manhattan          32        3.00              Coffee
1       Lower Manhattan          57        3.10                 Tea
2       Lower Manhattan          59        4.50  Drinking Chocolate
3       Lower Manhattan          22        2.00              Coffee
4       Lower Manhattan          57        3.10                 Tea
...                 ...         ...         ...                 ...
149111   Hell's Kitchen          44        2.50                 Tea
149112   Hell's Kitchen          49        3.00                 Tea
149113   Hell's Kitchen          45        3.00                 Tea
149114   Hell's Kitchen          40        3.75              Coffee
149115   Hell's Kitchen          64        0.80            Flavours

                 product_type               product_detail
0       Gourmet brewed coffee                  Ethiopia Rg
1             Brewed Chai tea     Spicy Eye Opener Chai Lg
2               Hot chocolate            Dark chocolate Lg
3                 Drip coffee  Our Old Time Diner Blend Sm
4             Brewed Chai tea     Spicy Eye Opener Chai Lg
...                       ...                          ...
149111      Brewed herbal tea                Peppermint Rg
149112       Brewed Black tea         English Breakfast Lg
149113      Brewed herbal tea                Peppermint Lg
149114       Barista Espresso                   Cappuccino
149115          Regular syrup               Hazelnut syrup

[149116 rows x 11 columns]>

In [20]:
# Display the first few rows of the dataframe
df.head()

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2025,7:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2025,7:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2025,7:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2025,7:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2025,7:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [21]:
## Display the last few rows of the dataframe
df.tail()

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
149111,149452,2025,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2025,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2025,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2025,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2025,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [22]:
# Display the number of rows and columns in the dataframe
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.info()

Rows : 149116
Columns : 11
<class 'pandas.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   year              149116 non-null  int64
 2   transaction_time  149116 non-null  str
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  str
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  str
 9   product_type      149116 non-null  str
 10  product_detail    149116 non-null  str
dtypes: float64(1), int64(5), str(5)
memory usage: 20.9 MB

In [23]:
df.describe()

,transaction_id,year,transaction_qty,store_id,product_id,unit_price
count,149116.000000,149116.0,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,2025.0,1.438276,5.342063,47.918607,3.382219
std,43153.600016,0.0,0.542509,2.074241,17.930020,2.658723
min,1.000000,2025.0,1.000000,3.000000,1.000000,0.800000
25%,37335.750000,2025.0,1.000000,3.000000,33.000000,2.500000
50%,74727.500000,2025.0,1.000000,5.000000,47.000000,3.000000
75%,112094.250000,2025.0,2.000000,8.000000,60.000000,3.750000
max,149456.000000,2025.0,8.000000,8.000000,87.000000,45.000000

In [24]:
# Checking Missing Values in Dataset